apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: "*"
    helm:
      skipCrds: true
      values: |
        prometheus:
          prometheusSpec:
            retention: 6h
            resources:
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                cpu: 500m
                memory: 512Mi
        alertmanager:
          alertmanagerSpec:
            resources:
              requests:
                cpu: 10m
                memory: 32Mi
              limits:
                cpu: 100m
                memory: 64Mi
        prometheusOperator:
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
        grafana:
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
          adminPassword: admin
          service:
            type: NodePort
            nodePort: 30090
          dashboardProviders:
            dashboardproviders.yaml:
              apiVersion: 1
              providers:
                - name: default
                  folder: ''
                  type: file
                  options:
                    path: /var/lib/grafana/dashboards/default
          dashboards:
            default:
              rabbitmq-overview:
                gnetId: 10991
                revision: 9
                datasource: Prometheus
              node-exporter-full:
                gnetId: 1860
                revision: 37
                datasource: Prometheus
              kubernetes-pods:
                gnetId: 15760
                revision: 29
                datasource: Prometheus
              kubernetes-cluster:
                gnetId: 7249
                revision: 1
                datasource: Prometheus
        kube-state-metrics:
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 64Mi
        nodeExporter:
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 64Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    syncOptions: [ CreateNamespace=true ]
    retry:
      limit: 5
      backoff: { duration: 15s, factor: 2, maxDuration: 3m }
